# Generated by Django 3.0.2 on 2020-02-01 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='slug_name',
        ),
    ]
